# Use an official Node runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install any needed packages specified in package.json
RUN npm install

# Make port 80 available to the world outside this container
EXPOSE 80

# Build the app for production
RUN npm run build

# Install `serve` to run the application
RUN npm install -g serve

# Run the app when the container launches
CMD ["serve", "-s", "build", "-l", "80"]
